# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kvitale/ReconsoleApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kvitale/ReconsoleApp/build

# Include any dependencies generated for this target.
include CMakeFiles/atmos-panner.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/atmos-panner.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/atmos-panner.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/atmos-panner.dir/flags.make

CMakeFiles/atmos-panner.dir/codegen:
.PHONY : CMakeFiles/atmos-panner.dir/codegen

CMakeFiles/atmos-panner.dir/main.cpp.o: CMakeFiles/atmos-panner.dir/flags.make
CMakeFiles/atmos-panner.dir/main.cpp.o: /home/kvitale/ReconsoleApp/main.cpp
CMakeFiles/atmos-panner.dir/main.cpp.o: CMakeFiles/atmos-panner.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/kvitale/ReconsoleApp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/atmos-panner.dir/main.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/atmos-panner.dir/main.cpp.o -MF CMakeFiles/atmos-panner.dir/main.cpp.o.d -o CMakeFiles/atmos-panner.dir/main.cpp.o -c /home/kvitale/ReconsoleApp/main.cpp

CMakeFiles/atmos-panner.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/atmos-panner.dir/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kvitale/ReconsoleApp/main.cpp > CMakeFiles/atmos-panner.dir/main.cpp.i

CMakeFiles/atmos-panner.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/atmos-panner.dir/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kvitale/ReconsoleApp/main.cpp -o CMakeFiles/atmos-panner.dir/main.cpp.s

CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o: CMakeFiles/atmos-panner.dir/flags.make
CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o: /home/kvitale/ReconsoleApp/AudioEngine.cpp
CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o: CMakeFiles/atmos-panner.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/kvitale/ReconsoleApp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o -MF CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o.d -o CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o -c /home/kvitale/ReconsoleApp/AudioEngine.cpp

CMakeFiles/atmos-panner.dir/AudioEngine.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/atmos-panner.dir/AudioEngine.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kvitale/ReconsoleApp/AudioEngine.cpp > CMakeFiles/atmos-panner.dir/AudioEngine.cpp.i

CMakeFiles/atmos-panner.dir/AudioEngine.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/atmos-panner.dir/AudioEngine.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kvitale/ReconsoleApp/AudioEngine.cpp -o CMakeFiles/atmos-panner.dir/AudioEngine.cpp.s

CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o: CMakeFiles/atmos-panner.dir/flags.make
CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o: /home/kvitale/ReconsoleApp/PipeWireOutput.cpp
CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o: CMakeFiles/atmos-panner.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/kvitale/ReconsoleApp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o -MF CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o.d -o CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o -c /home/kvitale/ReconsoleApp/PipeWireOutput.cpp

CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kvitale/ReconsoleApp/PipeWireOutput.cpp > CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.i

CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kvitale/ReconsoleApp/PipeWireOutput.cpp -o CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.s

CMakeFiles/atmos-panner.dir/UserInterface.cpp.o: CMakeFiles/atmos-panner.dir/flags.make
CMakeFiles/atmos-panner.dir/UserInterface.cpp.o: /home/kvitale/ReconsoleApp/UserInterface.cpp
CMakeFiles/atmos-panner.dir/UserInterface.cpp.o: CMakeFiles/atmos-panner.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/kvitale/ReconsoleApp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/atmos-panner.dir/UserInterface.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/atmos-panner.dir/UserInterface.cpp.o -MF CMakeFiles/atmos-panner.dir/UserInterface.cpp.o.d -o CMakeFiles/atmos-panner.dir/UserInterface.cpp.o -c /home/kvitale/ReconsoleApp/UserInterface.cpp

CMakeFiles/atmos-panner.dir/UserInterface.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/atmos-panner.dir/UserInterface.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/kvitale/ReconsoleApp/UserInterface.cpp > CMakeFiles/atmos-panner.dir/UserInterface.cpp.i

CMakeFiles/atmos-panner.dir/UserInterface.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/atmos-panner.dir/UserInterface.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/kvitale/ReconsoleApp/UserInterface.cpp -o CMakeFiles/atmos-panner.dir/UserInterface.cpp.s

# Object files for target atmos-panner
atmos__panner_OBJECTS = \
"CMakeFiles/atmos-panner.dir/main.cpp.o" \
"CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o" \
"CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o" \
"CMakeFiles/atmos-panner.dir/UserInterface.cpp.o"

# External object files for target atmos-panner
atmos__panner_EXTERNAL_OBJECTS =

atmos-panner: CMakeFiles/atmos-panner.dir/main.cpp.o
atmos-panner: CMakeFiles/atmos-panner.dir/AudioEngine.cpp.o
atmos-panner: CMakeFiles/atmos-panner.dir/PipeWireOutput.cpp.o
atmos-panner: CMakeFiles/atmos-panner.dir/UserInterface.cpp.o
atmos-panner: CMakeFiles/atmos-panner.dir/build.make
atmos-panner: CMakeFiles/atmos-panner.dir/compiler_depend.ts
atmos-panner: /usr/lib64/libpipewire-0.3.so
atmos-panner: CMakeFiles/atmos-panner.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/home/kvitale/ReconsoleApp/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Linking CXX executable atmos-panner"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/atmos-panner.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/atmos-panner.dir/build: atmos-panner
.PHONY : CMakeFiles/atmos-panner.dir/build

CMakeFiles/atmos-panner.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/atmos-panner.dir/cmake_clean.cmake
.PHONY : CMakeFiles/atmos-panner.dir/clean

CMakeFiles/atmos-panner.dir/depend:
	cd /home/kvitale/ReconsoleApp/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/kvitale/ReconsoleApp /home/kvitale/ReconsoleApp /home/kvitale/ReconsoleApp/build /home/kvitale/ReconsoleApp/build /home/kvitale/ReconsoleApp/build/CMakeFiles/atmos-panner.dir/DependInfo.cmake "--color=$(COLOR)" atmos-panner
.PHONY : CMakeFiles/atmos-panner.dir/depend

