# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/home/kvitale/ReconsoleApp -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2

CXX_FLAGS = -std=c++20 -Wall -Wextra -Wpedantic -D_REENTRANT -fno-strict-aliasing -fno-strict-overflow

