# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/home/kvitale/ReconsoleApp

CXX_FLAGS = -std=c++20 -Wall -Wextra -Wpedantic

